general:
  # The plugin tick speed in seconds (e.g. for room checks, spawner actions...)
  tick-frequency: 1
  # time in minutes that players can't be part of a dungeon party again
  player-lock-cooldown: 120
  # time in seconds that a dungeon needs to be sleeping in order to auto-reset. Use -1 to disable.
  auto-reset-time: 1800
  # maximum height for barriers
  max-barrier-height: 8
  # the sound that will be used if you activate boss music in a room
  boss-music: sound.battle_music
  # the length of the sound in ticks (for looping)
  boss-music-loop-length: 480
  # allow the command to warp to dungeons. Required a restart to take effect.
  allow-warp: false
  visualisation:
  dungeon-center:
    particle: SOUL_FIRE_FLAME
  room-edge:
    particle: FLAME
    density: 2
  spawner:
    particle: RAID_OMEN
  loot-chest:
    particle: HAPPY_VILLAGER
  lock-chest:
    particle: ANGRY_VILLAGER
  supply-chest:
    particle: SOUL
  barrier:
    particle: CAMPFIRE_COSY_SMOKE
  warp:
    particle: WITCH

###################################################
# +---------------------------------------------+ #
# |                   Towny                     | #
# +---------------------------------------------+ #
###################################################

# Optional settings if Towny is present on the server
# This will only apply to towns that have their dungeon metadata set 
# to a specific dungeon (using "/ta town <townname> setdungeon <dungeonname>")
# Valid placeholders are:
# {dungeon-name} {dungeon-description} {dungeon-status}

town-screen:
  enabled: true

###################################################
# +---------------------------------------------+ #
# |                  MapTowny                   | #
# +---------------------------------------------+ #
###################################################

# Optional settings if MapTowny is present on the server
# This will only apply to towns that have their dungeon metadata set 
# to a specific dungeon (using "/ta town <townname> setdungeon <dungeonname>")
# Valid placeholders are:
# {dungeon-id} {dungeon-name} {dungeon-description} {dungeon-status}

maptowny:
  show-custom-town-info: true
  dungeon-map-color: "#ff6940"
  dungeon-map-fill: "#ff6940"
  custom-town-info: |
    <center>
    <p style="font-size: 140%; font-weight: bold; line-height: 1em; margin-bottom: 5px">
      {dungeon-name}
    </p>
    <p style="font-size: 90%; font-weight: bold; line-height: 1em">
      DUNGEON
    </p>
    <hr />
    <object data="/images/dungeons/{dungeon-id}.jpg" type="image/png" style="width: 260px; height: 180px; margin-top: 5px">
      <img src="/images/og.png" alt="{dungeon-name}" style="width: 100%; height: auto">
    </object>
    <p>{dungeon-description}</p>
    <p><strong>Status:</strong> {dungeon-status}</p>
    </center>

