name: UnitedDungeons
version: 2.2.0
main: org.unitedlands.dungeons.UnitedDungeons
api-version: 1.21
description: A custom United Lands plugin for dungeon management.
author: Theriel_
depend: [UnitedLib]
softdepend: [MapTowny]
commands:
  uniteddungeons:
     description: Global UnitedDungeons player commands.
     aliases: [ud]
  udadmin:
     description: UnitedDungeons admin commands.
     aliases: [uda]
     permission: united.dungeons.admin
permissions:
  united.dungeons.admin:
     default: false