name: UnitedDungeons
version: 1.0.3
main: org.unitedlands.UnitedDungeons
api-version: 1.21
description: A custom United Lands plugin for dungeon management.
author: Theriel_
commands:
  ud:
     description: Global UnitedDungeons player commands.
     aliases: []
  uddungeon:
     description: Used to manage and play dungeons.
     aliases: [udd]
     permission: united.dungeons.admin
  udspawner:
     description: Used to manage dungeon spawners
     aliases: [uds]
     permission: united.dungeons.admin
permissions:
  united.dungeons.admin:
    default: false